import express from "express";
import abioticoColuna from './abioticoColuna.routes';
import campanha from "./campanha.routes";
import instituicao from "./instituicao.routes";
import reservatorio from "./reservatorio.routes";
import sitio from "./sitio.routes";
import campanhaPT from './campanhaPorTabela.routes';
import carbono from './carbono.routes';
import campoPT from './campoPorTabela.routes';
import concentracaoGA from './concentracaoGasAgua.routes';
import concentracaoGS from './concentracaoGasSedimento.routes';
import dadosPrecipitacao from './dadosPrecipitacao.routes';
import dadosRepresa from './dadosRepresa.routes';
import difusao from './difusao.routes';
import duplaDA from './duplaDessorcaoAgua.routes';
import fluxoBI from './fluxoBolhasInpe.routes';
import fluxoCarbono from './fluxoCarbono.routes';
import fluxoDifusivo from './fluxoDifusivo.routes';
import fluxoDInpe from './fluxoDifusivoInpe.routes';
import gasesEB from './gasesEmBolhas.routes';
import horiba from './horiba.routes';
import abioticoSuperficie from './abioticoSuperficie.routes';
import aguaMOS from './aguaMateriaOrganicaSedimento.routes'; 
import bioticoColuna from './bioticoColuna.routes';
import bioticoSuperficie from './bioticoSuperficie.routes';
import bolhas from './bolhas.routes';
import camaraSolo from './camaraSolo.routes'; 
import ionsNaAguaIDS from './ionsNaAguaIntersticialDoSedimento.routes'; 
import medidaCampoColuna from './medidacampoColuna.routes';
import medidaCSuperficie from './medidaCampoSuperficie.routes';
import nutrientesSedimento from './nutrientesSedimento.routes'; 
import parametrosBFAgua from './parametrosBiologicosFisicosAgua.routes'; 
import pfq from './pfq.routes';
import tabela from './tabela.routes';
import tc from './tc.routes';
import variaveisFQDaAgua from './variaveisFisicasQuimicasDaAgua.routes'; 

const router = express.Router();

router.use("/abiotico-coluna", abioticoColuna);
router.use("/campanha", campanha);
router.use("/instituicao", instituicao);
router.use("/reservatorio", reservatorio);
router.use("/sitio", sitio);
router.use("/campanha-por-tabela", campanhaPT);
router.use("/carbono", carbono);
router.use("/campo-por-tabela", campoPT);
router.use("/concentracao-gas-agua", concentracaoGA);
router.use("/concentracao-gas-sedimento", concentracaoGS);
router.use("/dados-precipitacao", dadosPrecipitacao);
router.use("/dados-represa", dadosRepresa);
router.use("/difusao", difusao);
router.use("/dupla-dessorcao-agua", duplaDA);
router.use("/fluxo-bolhas-inpe", fluxoBI);
router.use("/fluxo-carbono", fluxoCarbono);
router.use("/fluxo-difusivo", fluxoDifusivo); 
router.use("/fluxo-difusivo-inpe", fluxoDInpe); 
router.use("/gases-em-bolhas", gasesEB);
router.use("/horiba", horiba);
router.use("/abiotico-superficie", abioticoSuperficie);
router.use("/agua-materia-organica-sedimento", aguaMOS);
router.use("/biotico-coluna", bioticoColuna);
router.use("/biotico-superficie", bioticoSuperficie);
router.use("/bolhas", bolhas);
router.use("/camara-solo", camaraSolo);
router.use("/ions-na-agua-intersticial-do-sedimento", ionsNaAguaIDS);
router.use("/medida-campo-coluna", medidaCampoColuna);
router.use("/medida-campo-superficie", medidaCSuperficie);
router.use("/nutrientes-sedimento", nutrientesSedimento);
router.use("/parametros-biologicos-fisicos-agua", parametrosBFAgua);
router.use("/pfq", pfq);
router.use("/tabela", tabela);
router.use("/tc", tc);
router.use("/variaveis-fisicas-quimicas-da-agua", variaveisFQDaAgua);

export default router;